### ISSUE TITLE
Problems with installation(Mac OS X)

### ISSUE THREAD

**Issue by HD421** [mgeeky/burpContextAwareFuzzer#1]
Hi, when I'm trying to install your extension on mac I get following error: 
`java -cp jython-standalone-2.7.0.jar org.python.util.jython -m ensurepip --upgrade
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:jython-standalone-2.7.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
org.python.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
Traceback (most recent call last):
  File "jython-standalone-2.7.0.jar/Lib/runpy.py", line 161, in _run_module_as_main
  File "jython-standalone-2.7.0.jar/Lib/runpy.py", line 72, in _run_code
  File "jython-standalone-2.7.0.jar/Lib/ensurepip/__main__.py", line 4, in <module>
  File "jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 220, in _main
  File "jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 123, in bootstrap
  File "jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 45, in _run_pip
  File "pip-1.6-py2.py3-none-any.whl/pip/__init__.py", line 10, in <module>
  File "pip-1.6-py2.py3-none-any.whl/pip/util.py", line 13, in <module>
  File "pip-1.6-py2.py3-none-any.whl/pip/backwardcompat/__init__.py", line 115, in <module>
  File "jython-standalone-2.7.0.jar/Lib/distutils/sysconfig.py", line 28, in <module>
  File "jython-standalone-2.7.0.jar/Lib/posixpath.py", line 367, in realpath
  File "jython-standalone-2.7.0.jar/Lib/posixpath.py", line 373, in _joinrealpath
  File "jython-standalone-2.7.0.jar/Lib/posixpath.py", line 61, in isabs
AttributeError: 'NoneType' object has no attribute 'startswith'`

So do you have any other advices on how to install anything into jython .jar file?

**Comment by mgeeky** [comment]
Hi there @HD421 ,

Thanks for reporting this. I believe you are having some issues with the Jython's binary itself.
Try to look that traceback up on bug reports, like this one:
[issue28552](https://bugs.python.org/issue28552)
